
The following have been reloaded with a version change:
  1) NiaEnv/2018a => NiaEnv/2019b

Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 34, in create_sim_folder
    self.sim_subdir = save_subdir; os.makedirs( save_subdir )
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/sim0'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 34, in create_sim_folder
    self.sim_subdir = save_subdir; os.makedirs( save_subdir )
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/sim2'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 34, in create_sim_folder
    self.sim_subdir = save_subdir; os.makedirs( save_subdir )
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/sim0'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 34, in create_sim_folder
    self.sim_subdir = save_subdir; os.makedirs( save_subdir )
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/sim0'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 26, in create_sim_folder
    os.makedirs(self.figure_dir)
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/figures'
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 34, in create_sim_folder
    self.sim_subdir = save_subdir; os.makedirs( save_subdir )
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/sim24'
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 34, in create_sim_folder
    self.sim_subdir = save_subdir; os.makedirs( save_subdir )
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/sim22'
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 34, in create_sim_folder
    self.sim_subdir = save_subdir; os.makedirs( save_subdir )
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/sim31'
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 34, in create_sim_folder
    self.sim_subdir = save_subdir; os.makedirs( save_subdir )
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/sim32'
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 34, in create_sim_folder
    self.sim_subdir = save_subdir; os.makedirs( save_subdir )
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/sim45'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 34, in create_sim_folder
    self.sim_subdir = save_subdir; os.makedirs( save_subdir )
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/sim45'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 34, in create_sim_folder
    self.sim_subdir = save_subdir; os.makedirs( save_subdir )
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/sim45'
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 34, in create_sim_folder
    self.sim_subdir = save_subdir; os.makedirs( save_subdir )
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/sim48'
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 34, in create_sim_folder
    self.sim_subdir = save_subdir; os.makedirs( save_subdir )
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/sim48'
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 34, in create_sim_folder
    self.sim_subdir = save_subdir; os.makedirs( save_subdir )
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/sim48'
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 138, in <module>
    Model.create_sim_folder()
  File "/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/gillespie_models.py", line 34, in create_sim_folder
    self.sim_subdir = save_subdir; os.makedirs( save_subdir )
  File "/scinet/niagara/software/2019b/opt/base/python/3.6.8/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/sim_results/sir/sim49'
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)
Traceback (most recent call last):
  File "gillespie.py", line 142, in <module>
    gillespie(Model, max_time, num_generations, num_states, traj)
  File "gillespie.py", line 87, in gillespie
    simulation[0,:] = init_state.copy()
ValueError: could not broadcast input array from shape (2) into shape (30)

scontrol show jobid 3324129
JobId=3324129 JobName=gillespie-sir
   UserId=jbroths(3061232) GroupId=zilmana(6002070) MCS_label=N/A
   Priority=1676400 Nice=0 Account=rrg-zilmana QOS=normal
   JobState=COMPLETING Reason=NonZeroExitCode Dependency=(null)
   Requeue=0 Restarts=0 BatchFlag=1 Reboot=0 ExitCode=101:0
   RunTime=00:00:13 TimeLimit=1-00:00:00 TimeMin=N/A
   SubmitTime=2020-05-26T20:01:34 EligibleTime=2020-05-26T20:01:34
   AccrueTime=2020-05-26T20:01:34
   StartTime=2020-05-26T20:01:55 EndTime=2020-05-26T20:02:08 Deadline=N/A
   SuspendTime=None SecsPreSuspend=0 LastSchedEval=2020-05-26T20:01:55
   Partition=compute AllocNode:Sid=nia-login05:64181
   ReqNodeList=(null) ExcNodeList=(null)
   NodeList=nia2014
   BatchHost=nia2014
   NumNodes=1 NumCPUs=80 NumTasks=40 CPUs/Task=1 ReqB:S:C:T=0:0:*:*
   TRES=cpu=80,node=1,billing=40
   Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=*
   MinCPUsNode=1 MinMemoryNode=0 MinTmpDiskNode=0
   Features=[skylake|cascade] DelayBoot=00:00:00
   OverSubscribe=NO Contiguous=0 Licenses=(null) Network=(null)
   Command=/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/niagara_submit.sh
   WorkDir=/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie
   StdErr=/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/slurm-3324129.out
   StdIn=/dev/null
   StdOut=/gpfs/fs0/scratch/z/zilmana/jbroths/project-abundance/gillespie/slurm-3324129.out
   Power=

sacct -j 3324129
       JobID    JobName    Account    Elapsed  MaxVMSize     MaxRSS  SystemCPU    UserCPU ExitCode 
------------ ---------- ---------- ---------- ---------- ---------- ---------- ---------- -------- 
3324129      gillespie+ rrg-zilma+   00:00:13                        00:33.487  00:18.779    101:0 
3324129.bat+      batch rrg-zilma+   00:00:13    137364K      1176K  00:33.487  00:18.778    101:0 
3324129.ext+     extern rrg-zilma+   00:00:13    137128K       992K   00:00:00   00:00:00      0:0 
